# Generated by Django 6.0.5 on 2026-05-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_jobs', '0002_job_external_id_job_external_url_job_is_external_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Internship', 'Internship'), ('Trainee', 'Trainee')], max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Bangalore', 'Bangalore')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
